# Generated by Django 5.1.6 on 2025-10-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas', models.PositiveIntegerField(default=0, verbose_name='Total de Entradas')),
                ('salidas', models.PositiveIntegerField(default=0, verbose_name='Total de Salidas')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('ultima_entrada', models.DateTimeField(blank=True, null=True)),
                ('ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodegas.bodega')),
            ],
            options={
                'verbose_name': 'Inventario por Bodega',
                'verbose_name_plural': 'Inventarios por Bodega',
                'ordering': ['bodega', 'producto'],
            },
        ),
    ]
