# Generated by Django 5.1.6 on 2025-06-16 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariobodega',
            name='usuario_ultima_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario última entrada'),
        ),
        migrations.AddField(
            model_name='inventariobodega',
            name='usuario_ultima_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario última salida'),
        ),
    ]
