# Generated by Django 5.1.6 on 2025-02-24 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0003_alter_ciudad_activo_alter_ciudad_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id_usuario_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades_insertadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creo'),
        ),
    ]
