# Generated by Django 5.1.6 on 2025-10-20 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='id_usuario_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades_insertadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_usuario_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificó'),
        ),
    ]
