# Generated by Django 5.1.6 on 2025-06-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0004_alter_ciudad_id_usuario_insert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='id_usuario_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificó'),
        ),
    ]
