# Generated by Django 5.1.6 on 2025-09-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('contable', 'Contable'), ('almacen', 'Almacen'), ('empleado', 'Empleado')], default='Almacen', max_length=10),
        ),
    ]
