# Generated by Django 5.1.6 on 2025-09-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('contable', 'Contable'), ('almacen', 'Almacen')], default='Almacen', max_length=10),
        ),
    ]
