# Generated by Django 5.1.6 on 2025-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0002_compra_itemcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
