# Generated by Django 5.1.6 on 2025-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0003_alter_itemcompra_cantidad_recibida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('generada', 'generada'), ('recibida', 'recibida'), ('cancelada', 'cancelada')], default='generada', max_length=20),
        ),
    ]
