# Generated by Django 5.1.6 on 2025-05-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0002_alter_bodega_estado'),
        ('ordenes_compra', '0006_compra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Factura'),
        ),
    ]
