# Generated by Django 5.1.6 on 2025-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0007_compra_bodega_compra_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='Compra', max_length=20),
        ),
    ]
