# Generated by Django 5.1.6 on 2025-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0008_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
