# Generated by Django 5.1.6 on 2025-05-09 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0009_alter_compra_fecha_recepcion_and_more'),
        ('proveedores', '0004_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
