# Generated by Django 5.1.6 on 2025-05-12 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0010_compra_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='fecha_recepcion',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
