# Generated by Django 5.1.6 on 2025-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0011_rename_fecha_recepcion_compra_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('generada', 'generada'), ('recibida', 'recibida'), ('comprada', 'comprada'), ('cancelada', 'cancelada')], default='generada', max_length=20),
        ),
    ]
