# Generated by Django 5.1.6 on 2025-06-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0015_alter_compra_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(auto_now_add=True),
        ),
    ]
