# Generated by Django 5.1.6 on 2025-06-24 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0016_alter_compra_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='orden_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='ordenes_compra.ordencompra'),
        ),
    ]
