# Generated by Django 5.1.6 on 2025-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0017_alter_compra_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
