# Generated by Django 5.1.6 on 2025-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0018_alter_compra_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_documento',
            field=models.CharField(choices=[('OC', 'Orden de Compra'), ('TR', 'Traslado Interno')], default='OC', max_length=2),
        ),
    ]
