# Generated by Django 5.1.6 on 2025-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0019_ordencompra_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo_documento',
            field=models.CharField(choices=[('OC', 'Orden de Compra'), ('TRS', 'Traslado Interno')], default='OC', max_length=3),
        ),
    ]
