# Generated by Django 5.1.6 on 2025-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0021_alter_ordencompra_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo Documento'),
        ),
    ]
