# Generated by Django 5.1.6 on 2025-10-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0022_compra_tipo_documento'),
        ('ordenes_salida', '0006_salida_orden_compra_asociada'),
        ('productos', '0004_rename_id_usuario_creador_categoria_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiferenciaTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('diferencia', models.IntegerField()),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias', to='ordenes_compra.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias', to='ordenes_salida.salida')),
            ],
        ),
    ]
