# Generated by Django 5.1.6 on 2025-10-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEntregaDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('centro_costo', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('talla_camisa', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_camisa', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_pantalon', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('talla_zapatos', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_zapatos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cantidad_botas_caucho', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EntregaDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_entrega', models.CharField(blank=True, choices=[('ingreso', 'Por ingreso'), ('ley', 'Por ley')], max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaltanteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_faltante', models.PositiveIntegerField(help_text='Cantidad pendiente por entregar de este producto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado del faltante (Pendiente, Entregado o Cancelado)', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Faltante de Entrega',
                'verbose_name_plural': 'Faltantes de Entregas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialIngresoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Ingreso',
                'verbose_name_plural': 'Historial de Ingresos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
