# Generated by Django 5.1.6 on 2025-07-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('centro_costo', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('talla_camisa', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_camisa', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_pantalon', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('talla_zapatos', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_zapatos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cantidad_botas_caucho', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
