# Generated by Django 5.1.6 on 2025-07-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0001_initial'),
        ('grupos_dotacion', '0005_grupodotacionproducto_activo'),
        ('productos', '0003_categoria_id_usuario_creador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='dotacion_empleado.empleadodotacion')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos_dotacion.grupodotacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
        ),
    ]
