# Generated by Django 5.1.6 on 2025-10-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudades', '0001_initial'),
        ('clientes', '0001_initial'),
        ('dotacion_empleado', '0001_initial'),
        ('grupos_dotacion', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentregadotacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='empleadodotacion',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grupos_dotacion.cargo'),
        ),
        migrations.AddField(
            model_name='empleadodotacion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ciudades.ciudad'),
        ),
        migrations.AddField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='entregadotacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='dotacion_empleado.empleadodotacion'),
        ),
        migrations.AddField(
            model_name='entregadotacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos_dotacion.grupodotacion'),
        ),
        migrations.AddField(
            model_name='detalleentregadotacion',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='dotacion_empleado.entregadotacion'),
        ),
        migrations.AddField(
            model_name='faltanteentrega',
            name='entrega',
            field=models.ForeignKey(help_text='Entrega original a la que pertenece este faltante', on_delete=django.db.models.deletion.CASCADE, related_name='faltantes', to='dotacion_empleado.entregadotacion'),
        ),
        migrations.AddField(
            model_name='faltanteentrega',
            name='producto',
            field=models.ForeignKey(help_text='Producto que no pudo ser entregado inicialmente', on_delete=django.db.models.deletion.CASCADE, related_name='faltantes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='historialingresoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ingresos', to='dotacion_empleado.empleadodotacion'),
        ),
    ]
