# Generated by Django 5.1.6 on 2025-07-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0002_entregadotacion'),
        ('productos', '0003_categoria_id_usuario_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregadotacion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='entregadotacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='entregadotacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetalleEntregaDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='dotacion_empleado.entregadotacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
    ]
