# Generated by Django 5.1.6 on 2025-10-23 19:30

import applications.dotacion_empleado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregadotacion',
            name='fecha_entrega',
            field=models.DateTimeField(default=applications.dotacion_empleado.models.redondear_a_minuto),
        ),
    ]
