# Generated by Django 5.1.6 on 2025-10-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0003_initial'),
        ('dotacion_empleado', '0003_alter_entregadotacion_fecha_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregadotacion',
            old_name='grupo',
            new_name='grupo_dotacion',
        ),
        migrations.AddField(
            model_name='entregadotacion',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to='bodegas.bodega', verbose_name='Bodega de salida'),
        ),
    ]
