# Generated by Django 5.1.6 on 2025-07-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_usuario_editor'),
        ('dotacion_empleado', '0003_remove_entregadotacion_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
