# Generated by Django 5.1.6 on 2025-07-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0004_alter_empleadodotacion_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
    ]
