# Generated by Django 5.1.6 on 2025-07-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_usuario_editor'),
        ('dotacion_empleado', '0005_alter_empleadodotacion_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
