# Generated by Django 5.1.6 on 2025-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0007_alter_empleadodotacion_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadodotacion',
            name='ciudad',
        ),
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
    ]
