# Generated by Django 5.1.6 on 2025-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0008_remove_empleadodotacion_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadodotacion',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
