# Generated by Django 5.1.6 on 2025-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0009_empleadodotacion_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadodotacion',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
