# Generated by Django 5.1.6 on 2025-08-12 19:59

import applications.dotacion_empleado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0010_alter_empleadodotacion_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregadotacion',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[applications.dotacion_empleado.models.validar_periodo]),
        ),
    ]
