# Generated by Django 5.1.6 on 2025-08-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0011_entregadotacion_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregadotacion',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
