# Generated by Django 5.1.6 on 2025-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0012_alter_entregadotacion_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregadotacion',
            name='tipo_entrega',
            field=models.CharField(choices=[('ingreso', 'Por ingreso'), ('ley', 'Por ley')], default='ingreso', max_length=10),
        ),
    ]
