# Generated by Django 5.1.6 on 2025-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0013_entregadotacion_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregadotacion',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('ingreso', 'Por ingreso'), ('ley', 'Por ley')], max_length=10, null=True),
        ),
    ]
