# Generated by Django 5.1.6 on 2025-08-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0014_alter_entregadotacion_tipo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIngresoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ingresos', to='dotacion_empleado.empleadodotacion')),
            ],
            options={
                'verbose_name': 'Historial de Ingreso',
                'verbose_name_plural': 'Historial de Ingresos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
