# Generated by Django 5.1.6 on 2025-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0016_alter_empleadodotacion_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadodotacion',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
