# Generated by Django 5.1.6 on 2025-09-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0005_ciudad_id_usuario_update'),
        ('clientes', '0003_alter_cliente_ciudad'),
        ('dotacion_empleado', '0017_alter_empleadodotacion_ciudad_and_more'),
        ('grupos_dotacion', '0006_remove_grupodotacionproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grupos_dotacion.cargo'),
        ),
        migrations.AlterField(
            model_name='empleadodotacion',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ciudades.ciudad'),
        ),
        migrations.AlterField(
            model_name='empleadodotacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
