# Generated by Django 5.1.6 on 2025-09-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0018_alter_empleadodotacion_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregadotacion',
            name='estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
