# Generated by Django 5.1.6 on 2025-09-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion_empleado', '0019_entregadotacion_estado'),
        ('productos', '0004_rename_id_usuario_creador_categoria_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltanteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_faltante', models.PositiveIntegerField(help_text='Cantidad pendiente por entregar de este producto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado del faltante (Pendiente, Entregado o Cancelado)', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('entrega', models.ForeignKey(help_text='Entrega original a la que pertenece este faltante', on_delete=django.db.models.deletion.CASCADE, related_name='faltantes', to='dotacion_empleado.entregadotacion')),
                ('producto', models.ForeignKey(help_text='Producto que no pudo ser entregado inicialmente', on_delete=django.db.models.deletion.CASCADE, related_name='faltantes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Faltante de Entrega',
                'verbose_name_plural': 'Faltantes de Entregas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
