# Generated by Django 5.1.6 on 2025-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('Unidad', 'Unidad')], max_length=100, null=True),
        ),
    ]
