# Generated by Django 5.1.6 on 2025-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('camisas', 'CAMISAS'), ('pantalones', 'PANTALONES'), ('botas', 'BOTAS')], max_length=100, null=True),
        ),
    ]
