# Generated by Django 5.1.6 on 2025-08-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_id_usuario_creador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='id_usuario_creador',
            new_name='id_usuario',
        ),
    ]
