# Generated by Django 5.1.6 on 2025-08-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0005_ciudad_id_usuario_update'),
        ('clientes', '0002_cliente_usuario_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudades.ciudad'),
        ),
    ]
