# Generated by Django 5.1.6 on 2025-07-08 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_dotacion', '0001_initial'),
        ('productos', '0003_categoria_id_usuario_creador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupodotacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='grupodotacion',
            name='usuario_creador',
        ),
        migrations.AddField(
            model_name='grupodotacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupodotacion',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10),
        ),
        migrations.CreateModel(
            name='GrupoDotacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='grupos_dotacion.grupodotacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
