# Generated by Django 5.1.6 on 2025-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_dotacion', '0002_remove_grupodotacion_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
    ]
