# Generated by Django 5.1.6 on 2025-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0005_ciudad_id_usuario_update'),
        ('grupos_dotacion', '0003_cargo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupodotacion',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='grupodotacion',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='grupodotacion',
            name='cargos',
            field=models.ManyToManyField(to='grupos_dotacion.cargo'),
        ),
        migrations.AddField(
            model_name='grupodotacion',
            name='ciudades',
            field=models.ManyToManyField(to='ciudades.ciudad'),
        ),
    ]
