# Generated by Django 5.1.6 on 2025-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_dotacion', '0004_remove_grupodotacion_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodotacionproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
