# Generated by Django 5.1.6 on 2025-08-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_dotacion', '0005_grupodotacionproducto_activo'),
        ('productos', '0003_categoria_id_usuario_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupodotacionproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='grupodotacionproducto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='grupodotacionproducto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='grupos_dotacion.grupodotacion'),
        ),
    ]
