# Generated by Django 5.1.6 on 2025-05-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_salida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsalida',
            old_name='cantidad_recibida',
            new_name='cantidad',
        ),
    ]
