# Generated by Django 5.1.6 on 2025-10-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0002_initial'),
        ('clientes', '0001_initial'),
        ('ordenes_compra', '0001_initial'),
        ('ordenes_salida', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsalida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='salida',
            name='bodegaEntrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='salida',
            name='bodegaSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salida', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='salida',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='salida',
            name='orden_compra_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_relacionadas', to='ordenes_compra.ordencompra'),
        ),
    ]
