# Generated by Django 5.1.6 on 2025-05-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0002_alter_bodega_estado'),
        ('ordenes_salida', '0002_rename_cantidad_recibida_itemsalida_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='bodega',
            new_name='bodegaSalida',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='salida',
            name='bodegaEntrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada', to='bodegas.bodega'),
        ),
    ]
