# Generated by Django 5.1.6 on 2025-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_salida', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='estado',
            field=models.CharField(default='Salida', max_length=30),
        ),
    ]
