# Generated by Django 5.1.6 on 2025-06-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_salida', '0004_salida_usuario_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tipo_documento',
            field=models.CharField(max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
