# Generated by Django 5.1.6 on 2025-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_salida', '0004_alter_salida_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tipo_documento',
            field=models.CharField(max_length=5, verbose_name='Tipo de Documento'),
        ),
    ]
