# Generated by Django 5.1.6 on 2025-10-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0020_alter_ordencompra_tipo_documento'),
        ('ordenes_salida', '0005_alter_salida_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='orden_compra_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_relacionadas', to='ordenes_compra.ordencompra'),
        ),
    ]
