# Generated by Django 5.1.6 on 2025-10-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_salida', '0006_salida_orden_compra_asociada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_salida', to='ordenes_salida.salida'),
        ),
    ]
