# Generated by Django 5.1.6 on 2025-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='direccion',
            field=models.CharField(),
        ),
    ]
