# Generated by Django 5.1.6 on 2025-10-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='id_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='ciudades.ciudad'),
        ),
    ]
