# Generated by Django 5.1.6 on 2025-10-20 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='id_usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodega',
            name='id_usuario_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_editadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
